### ISSUE TITLE
operation-failed: MINOR: NETCONF #265: Unable to open file

### ISSUE THREAD

**Issue by yongz2** [cisco-ie/anx#11]
I am trying to use anx connect with an nokia nx os device by netconf.
Seems it have already established connection but failed to get schema.
Some errors like following occured:
(operation-failed: MINOR: NETCONF #265: Unable to open file - cf3:/YANG/nokia-state-svc-ies.yang )

![image](https://user-images.githubusercontent.com/37018182/62062273-46bbed80-b25b-11e9-9f6e-749e0fe07564.png)

why it;s said "unable to open file", do I need to grant user some privilege when open these files?

**Comment by sbyx** [comment]
This error is coming from your device when ANX is trying to fetch a yang-model via the NETCONF get-schema operation. Since the error is device specific I cannot really help you on this matter, I can just tell you that the model is ignored in ANX and should not affect the usability of other models (except the ones that try to import the failed model). So you can possibly ignore the issue unless you care about that specific model.

So on device side make sure the NETCONF get-schema operation is supported for the models you care about then ANX should start working as well.
